# Generated by Django 4.2.13 on 2024-07-13 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_registered_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='registered_on',
        ),
    ]
