# Generated by Django 4.2.13 on 2024-07-14 00:01

from django.db import migrations, models
import django.db.models.deletion
from django.db import migrations
from django.contrib.auth.models import User

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('core', '0003_remove_customer_registered_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]



def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.create_superuser(username='admin', email='admin@inventra.com', password='pass123')

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0005_auto_20240714_0301.py'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
