# Generated by Django 4.2.13 on 2024-07-14 02:01

from django.db import migrations
from django.contrib.auth.models import User

def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser(username='admin', email='admin@example.com', password='adminpassword')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_orderitem_product_delete_product'),
    ]


    operations = [
        migrations.RunPython(create_superuser),
    ]
