# Generated by Django 4.2.13 on 2024-07-14 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_orderitem_product_delete_product'),
    ]

    operations = [
    ]
